name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - Chart.yaml
      - templates/**
      - values.yaml
      - values.schema.json

jobs:
  release:
    uses: ./.github/workflows/helm-oci-release.yaml
    permissions:
      contents: write
      packages: write
    with:
      oci_registry: ghcr.io/comet-ml
    secrets:
      oci_password: ${{ secrets.GITHUB_TOKEN }}
