name: Verify Chart Version Update
run-name: Verify Chart Version Update for PR #${{ github.event.number }} by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main
    paths:
      - Chart.yaml
      - templates/**
      - values.yaml
      - values.schema.json

jobs:
  verify-version:
    uses: ./.github/workflows/helm-verify-chart-version.yaml
    permissions:
      contents: read
    # chart_path defaults to '.' which is correct for this repo
